config/routes.rb
Godzilla::Application.routes.draw do
  resources :resources
  resources :epics
  resources :products
  get 'product_roadmap' => 'roadmap#products'
  get 'product_roadmap_parallel' => 'roadmap#products_parallel'

  root :to => 'products#index'
end

app/views/resources/_form.html.haml
= simple_form_for @resource, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :capacity
  = f.input :color
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), resources_path, :class => 'btn'

app/views/resources/edit.html.haml
- model_class = Resource
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/resources/index.html.haml
- model_class = Resource
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:capacity)
      %th= model_class.human_attribute_name(:color)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @resources.each do |resource|
      %tr
        %td= link_to resource.title, resource_path(resource)
        %td= resource.capacity
        %td{style: "color: white; background: #{resource.color};"}= resource.color
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_resource_path(resource), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), resource_path(resource), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_resource_path, :class => 'btn btn-primary'

app/views/resources/new.html.haml
- model_class = Resource
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/resources/show.html.haml
- model_class = Resource
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @resource.title
%p
  %strong= model_class.human_attribute_name(:capacity) + ':'
  %br
  = @resource.capacity

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), resources_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_resource_path(@resource), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), resource_path(@resource), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'