config/routes.rb
Godzilla::Application.routes.draw do
  resources :resources
  resources :epics
  resources :products
  get 'product_roadmap' => 'roadmap#products'
  get 'product_roadmap_parallel' => 'roadmap#products_parallel'

  root :to => 'products#index'
end

app/models/epic.rb
class Epic < ActiveRecord::Base
  attr_accessible :priority, :stake_holders, :title, :description, :product_id, :epic_resources_attributes
  
  belongs_to :product
  
  has_many :epic_resources

  accepts_nested_attributes_for :epic_resources, :allow_destroy => true

  def estimate_for(resource)
    estimate = 0
    self.epic_resources.where(resource_id: resource.id).each do |er|
      estimate += er.time_estimation
    end
    estimate
  end
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  # GET /epics
  # GET /epics.json
  def index
    @epics = Epic.order('product_id, priority, stake_holders').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @epics }
    end
  end

  # GET /epics/1
  # GET /epics/1.json
  def show
    @epic = Epic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @epic }
    end
  end

  # GET /epics/new
  # GET /epics/new.json
  def new
    @epic = Epic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @epic }
    end
  end

  # GET /epics/1/edit
  def edit
    @epic = Epic.find(params[:id])
  end

  # POST /epics
  # POST /epics.json
  def create
    @epic = Epic.new(params[:epic])

    respond_to do |format|
      if @epic.save
        format.html { redirect_to @epic, notice: 'Epic was successfully created.' }
        format.json { render json: @epic, status: :created, location: @epic }
      else
        format.html { render action: "new" }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /epics/1
  # PUT /epics/1.json
  def update
    @epic = Epic.find(params[:id])

    respond_to do |format|
      if @epic.update_attributes(params[:epic])
        format.html { redirect_to @epic, notice: 'Epic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.json
  def destroy
    @epic = Epic.find(params[:id])
    @epic.destroy

    respond_to do |format|
      format.html { redirect_to epics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/epics_helper.rb
module EpicsHelper
end

app/views/epics/_form.html.haml
= simple_nested_form_for @epic, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :priority
  = f.association :product
  = f.input :description
  = f.input :stake_holders

  = f.fields_for :epic_resources do |epic_resource_form|
    = epic_resource_form.association :resource
    = epic_resource_form.input :time_estimation
    = epic_resource_form.link_to_remove "Remove this resource"
  %p= f.link_to_add "Assign an additional resource", :epic_resources

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), epics_path, :class => 'btn'

app/views/epics/_list.html.haml
- model_class = Epic
= link_to t('.new', :default => t("helpers.links.new")), new_epic_path, :class => 'btn btn-primary'
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:priority)
      %th= model_class.human_attribute_name(:product)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:stake_holders)
      - Resource.all.each do |resource|
        %th= "#{resource.title} IDM"
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - epics.each do |epic|
      %tr
        %td= epic.priority
        %td= epic.product.title unless epic.product.blank?
        %td= link_to epic.title, epic_path(epic)
        %td= epic.stake_holders
        - Resource.all.each do |resource|
          %th= epic.estimate_for(resource)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_epic_path(epic), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), epic_path(epic), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_epic_path, :class => 'btn btn-primary'

app/views/epics/edit.html.haml
- model_class = Epic
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/epics/index.html.haml
- model_class = Epic
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
= render :partial => 'list', locals: { epics: @epics }

app/views/epics/new.html.haml
- model_class = Epic
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/epics/show.html.haml
- model_class = Epic
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @epic.title
%p
  %strong= model_class.human_attribute_name(:priority) + ':'
  %br
  = @epic.priority
%p
  %strong= model_class.human_attribute_name(:product) + ':'
  %br
  = @epic.product.title unless @epic.product.blank?
%p
  %strong= model_class.human_attribute_name(:stake_holders) + ':'
  %br
  = @epic.stake_holders
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @epic.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), epics_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_epic_path(@epic), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), epic_path(@epic), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'