config/routes.rb
Godzilla::Application.routes.draw do
  resources :resources
  resources :epics
  resources :products
  get 'product_roadmap' => 'roadmap#products'
  get 'product_roadmap_parallel' => 'roadmap#products_parallel'

  root :to => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :features, :priority, :scope, :title, :vision

  has_many :epics

  def estimate_for(resource)
    estimate = 0
    self.epics.each do |epic|
      estimate += epic.estimate_for(resource)
    end
    estimate
  end

  def longest_estimate
    longest_estimate = { resource: nil, estimate: 0 }
    Resource.all.each do |r|
      # divide estimate by IDM (capacity should be per)
      estimate = self.estimate_for(r)/r.capacity
      longest_estimate = {resource: r, estimate: estimate} if estimate > longest_estimate[:estimate]
    end
    return longest_estimate
  end

  def resources_for_pipeline
    resources = {}
    Resource.all.each do |r|
      resources[r] = (self.estimate_for(r)/r.capacity).to_i
    end
    return resources
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.order('priority').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @epics = @product.epics.order('priority')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= simple_form_for @product, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :priority
  = f.input :vision
  = f.input :scope
  = f.input :features
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn'

app/views/products/edit.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/products/index.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:priority)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:vision)
      %th= model_class.human_attribute_name(:scope)
      - Resource.all.each do |resource|
        %th= "#{resource.title} IDM"
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @products.each do |product|
      %tr
        %td= product.priority
        %td= link_to product.title, product_path(product)
        %td= product.vision
        %td= product.scope
        - Resource.all.each do |resource|
          %th= product.estimate_for(resource)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary'

app/views/products/new.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/products/show.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @product.title
%p
  %strong= model_class.human_attribute_name(:priority) + ':'
  %br
  = @product.priority
%p
  %strong= model_class.human_attribute_name(:vision) + ':'
  %br
  = @product.vision
%p
  %strong= model_class.human_attribute_name(:scope) + ':'
  %br
  = @product.scope
%p
  %strong= model_class.human_attribute_name(:features) + ':'
  %br
  = @product.features

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

.page-header
  %h1=t '.title', :default => "Epics of Product: #{@product.title}"
= render :partial => 'epics/list', locals: { epics: @epics }