config/routes.rb
Godzilla::Application.routes.draw do
  resources :resources
  resources :epics
  resources :products
  get 'product_roadmap' => 'roadmap#products'
  get 'product_roadmap_parallel' => 'roadmap#products_parallel'

  root :to => 'products#index'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Godzilla"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
            %a.brand(href="#{root_path}") Godzilla
          .container.nav-collapse
            %ul.nav
              %li= link_to "Products (#{Product.count})", products_path
              %li= link_to "Epics (#{Epic.count})", epics_path
              %li= link_to "Resources", resources_path
              %li |
              %li= link_to "Roadmap Items", product_roadmap_path
              %li= link_to "Roadmap", product_roadmap_parallel_path

    .container-fluid

      .row-fluid
        .span10.offset1
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Rogue Squadron 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"